[2025-08-19T15:17:36.755+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia permission to 509
[2025-08-19T15:17:36.756+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia'
[2025-08-19T15:17:36.794+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia permission to 509
[2025-08-19T15:17:36.795+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia'
[2025-08-19T15:17:36.837+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2025-08-19T15:17:33.958063+00:00 [queued]>
[2025-08-19T15:17:36.847+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2025-08-19T15:17:33.958063+00:00 [queued]>
[2025-08-19T15:17:36.847+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-08-19T15:17:36.860+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2025-08-19 15:17:33.958063+00:00
[2025-08-19T15:17:36.864+0000] {standard_task_runner.py:57} INFO - Started process 45 to run task
[2025-08-19T15:17:36.868+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2025-08-19T15:17:33.958063+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmp43g5ph3f']
[2025-08-19T15:17:36.870+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask extract_data_from_wikipedia
[2025-08-19T15:17:36.932+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia permission to 509
[2025-08-19T15:17:36.932+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:17:33.958063+00:00/task_id=extract_data_from_wikipedia'
[2025-08-19T15:17:36.945+0000] {task_command.py:410} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2025-08-19T15:17:33.958063+00:00 [running]> on host 2c92672f7c81
[2025-08-19T15:17:37.031+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Chayuthpong31' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T15:17:33.958063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T15:17:33.958063+00:00'
[2025-08-19T15:17:37.574+0000] {logging_mixin.py:149} INFO - Getting wikipedia page.... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2025-08-19T15:17:38.147+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipelines.py", line 38, in extract_wikipedia_data
    'region':tds[2].text,
IndexError: list index out of range
[2025-08-19T15:17:38.162+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20250819T151733, start_date=20250819T151736, end_date=20250819T151738
[2025-08-19T15:17:38.173+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task extract_data_from_wikipedia (list index out of range; 45)
[2025-08-19T15:17:38.206+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-08-19T15:17:38.225+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
