[2025-08-19T15:15:51.057+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia permission to 509
[2025-08-19T15:15:51.058+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia'
[2025-08-19T15:15:51.126+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia permission to 509
[2025-08-19T15:15:51.127+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia'
[2025-08-19T15:15:51.182+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2025-08-19T15:15:46.477142+00:00 [queued]>
[2025-08-19T15:15:51.190+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2025-08-19T15:15:46.477142+00:00 [queued]>
[2025-08-19T15:15:51.190+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-08-19T15:15:51.201+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): extract_data_from_wikipedia> on 2025-08-19 15:15:46.477142+00:00
[2025-08-19T15:15:51.206+0000] {standard_task_runner.py:57} INFO - Started process 23 to run task
[2025-08-19T15:15:51.210+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'wikipedia_flow', 'extract_data_from_wikipedia', 'manual__2025-08-19T15:15:46.477142+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/wikipedia_flow.py', '--cfg-path', '/tmp/tmpv_unahyx']
[2025-08-19T15:15:51.212+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask extract_data_from_wikipedia
[2025-08-19T15:15:51.274+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia permission to 509
[2025-08-19T15:15:51.274+0000] {logging_mixin.py:149} INFO - Failed to change /opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=wikipedia_flow/run_id=manual__2025-08-19T15:15:46.477142+00:00/task_id=extract_data_from_wikipedia'
[2025-08-19T15:15:51.287+0000] {task_command.py:410} INFO - Running <TaskInstance: wikipedia_flow.extract_data_from_wikipedia manual__2025-08-19T15:15:46.477142+00:00 [running]> on host 2c92672f7c81
[2025-08-19T15:15:51.387+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Chayuthpong31' AIRFLOW_CTX_DAG_ID='wikipedia_flow' AIRFLOW_CTX_TASK_ID='extract_data_from_wikipedia' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T15:15:46.477142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T15:15:46.477142+00:00'
[2025-08-19T15:15:53.189+0000] {logging_mixin.py:149} INFO - Getting wikipedia page.... https://en.wikipedia.org/wiki/List_of_association_football_stadiums_by_capacity
[2025-08-19T15:15:54.016+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/wikipedia_pipelines.py", line 28, in extract_wikipedia_data
    rows = get_wikipedia_data(html)
  File "/opt/airflow/pipelines/wikipedia_pipelines.py", line 18, in get_wikipedia_data
    table = soup.find_all("table", attrs={"class":"wikitable sortable"})[0]
IndexError: list index out of range
[2025-08-19T15:15:54.031+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=wikipedia_flow, task_id=extract_data_from_wikipedia, execution_date=20250819T151546, start_date=20250819T151551, end_date=20250819T151554
[2025-08-19T15:15:54.044+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task extract_data_from_wikipedia (list index out of range; 23)
[2025-08-19T15:15:54.075+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-08-19T15:15:54.095+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
